#!/usr/bin/env bash

if [[ -z "$USER_ID" ]]; then
    echo "strawman needs your local user id. Please make sure to define the environment variable 'export USER_ID=$(id -u)'" 1>&2
    exit 1
fi


if [[ -z "$GROUP_ID" ]]; then
    echo "strawman needs your local group id. Please make sure to define the environment variable 'export GROUP_ID=$(id -g)'" 1>&2
    exit 1
fi

STRAWMAN_USERNAME=strawman

STRAWMAN_DIR=/app

STRAWMAN_PORT=${STRAWMAN_PORT:"8080"}
STRAWMAN_ENDPOINT=https://openformation.io
STRAWMAN_WORKSPACE_DIR=/strawman
STRAWMAN_SNAPSHOT_DIR=/strawman/snapshots
STRAWMAN_DENO_PERMISSIONS=${STRAWMAN_DENO_PERMISSIONS:="--allow-net --allow-read=$STRAWMAN_WORKSPACE_DIR,$STRAWMAN_SNAPSHOT_DIR --allow-write=$STRAWMAN_SNAPSHOT_DIR"}

cd $STRAWMAN_DIR

addgroup --gid ${GROUP_ID} $STRAWMAN_USERNAME >/dev/null || true
adduser --disabled-password --gecos '' --uid ${USER_ID} --gid ${GROUP_ID} $STRAWMAN_USERNAME >/dev/null || true

mkdir -p $STRAWMAN_SNAPSHOT_DIR
chown $USER_ID:$GROUP_ID -R $STRAWMAN_WORKSPACE_DIR

args="$@"

su - $STRAWMAN_USERNAME -c "cd $STRAWMAN_DIR && deno run $STRAWMAN_DENO_PERMISSIONS modules/strawman-cli/cli.ts $args -s $STRAWMAN_SNAPSHOT_DIR"
